name: Build ShareNX

on: [push]
jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkita64

    steps:
    - uses: actions/checkout@v1
    - name: Update repo.
      run: |
        sed -i 's/git@github.com:/git:\/\/github.com\//' .gitmodules
        git submodule update --init --recursive
        
    - name: Building ShareNX
      run: |
        source /etc/profile.d/devkit-env.sh
        make -j$(nproc)