name: Build ShareNX

on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update repo.
      run: |
        sed -i 's/git@github.com:/git:\/\/github.com\//' .gitmodules
        git submodule update --init --recursive
        
    - name: Install devkitpro
      run: |
        wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb
        sudo dpkg -i devkitpro-pacman.deb
        sudo dkp-pacman -S $(dkp-pacman -Ssq switch-*) --noconfirm

    - name: Build and install libnx master
      run: |
        export DEVKITPRO=/opt/devkitpro
        export DEVKITARM=${DEVKITPRO}/devkitARM
        export DEVKITPPC=${DEVKITPRO}/devkitPPC
        export PATH=${DEVKITPRO}/tools/bin:$PATH
        git clone https://github.com/switchbrew/libnx.git
        sudo make -C libnx install -j$(nproc)
        
    - name: Building ShareNX
      run: |
        export DEVKITPRO=/opt/devkitpro
        export DEVKITARM=${DEVKITPRO}/devkitARM
        export DEVKITPPC=${DEVKITPRO}/devkitPPC
        export PATH=${DEVKITPRO}/tools/bin:$PATH
        make -j$(nproc)